# =========================================================================================
# Global Imports
# =========================================================================================
import sys
from tkinter import messagebox
# ============================================================================================
# FUNCTIONS
# ============================================================================================


def takeincolumnsfile(function_filepath):
    """
    Take in the columns1.txt and columns2.txt generated by server.py that contains the headers for each csv file
    return the values found within
    :param function_filepath: filepath of function.py (served as reference to where the column.txt is found)
    :return: 2 lists, each containing a list of headers
    """
    # Open and get the list of headers
    file = open(function_filepath+"/resources/columns1.txt", "r")
    input_list_1 = file.readlines()
    input_list_1 = input_list_1[0].strip(' ')
    file.close()

    file = open(function_filepath + "/resources/columns2.txt", "r")
    input_list_2 = file.readlines()
    input_list_2 = input_list_2[0].strip(' ')
    file.close()
    return input_list_1, input_list_2


def verify_headers(headers_selection, fn_filepath):
    """
    Take in the columns.txt files generated by the server.py (contains header list)
    compare the user input for the headers and verify if all the headers are in 1 or 2 csv files.

    Error conditions:
    1.If different headers come from 2 different csv files with different headers, terminate.
    2.If the exact same header is found in both csv files, will ask user to select which one to process

    :param headers_selection:
    :param fn_filepath: filepath of function.py (served as reference to where the column.txt is found)
    :return: Either number corresponding to the 1st or 2nd csv file, or return error message
    """
    outcome_list = []
    headers_list = headers_selection.split(',')
    csv1_headers, csv2_headers = takeincolumnsfile(fn_filepath)

    # Compare the user input with the csv headers that were loaded
    for entry in headers_list:
        if entry in csv1_headers:
            if entry in csv2_headers:
                outcome_list.append(0)                                  # If entry found in both columns.txt
            else:
                outcome_list.append(1)  # If entry found in only columns1.txt
        else:
            if entry in csv2_headers:
                outcome_list.append(2)                                  # If entry found only in columns2.txt
    print(outcome_list)
    # Checking for error conditions
    if 0 in outcome_list:
        # If header present in both csv, ask user to select which one to select
        answer = messagebox.askquestion("Confirmation", "Header option found in both chosen csv. Choose: \n Yes: To process the first csv\n No: To process the second csv")
        if answer == "yes":
            return 1
        elif answer == "no":
            return 2
    else:
        if 1 in outcome_list:                                           # if 2 different headers found in 2 different csv file, terminate
            if 2 in outcome_list:
                sys.exit(messagebox.showerror("Error", "Different headers found in 2 different csv files. Unable to process further \nProgram will be terminated."))
            else:
                return outcome_list[0]
        else:
            return  outcome_list[0]
